export const typographyRules = Object.entries({
  'font-heading': {
    'font-family': 'var(--font-heading)',
  },
  'font-body': {
    'font-family': 'var(--font-body)',
  },
  'text-h1': {
    'font-family': 'var(--font-heading)',
    'text-transform': 'none',
    'font-size': '6rem',
    'font-weight': '300',
    'line-height': '1',
    'letter-spacing': '-.015625em',
  },
  'text-h2': {
    'font-family': 'var(--font-heading)',
    'text-transform': 'none',
    'font-size': '3.75rem',
    'font-weight': '300',
    'line-height': '1',
    'letter-spacing': '-.0083333333em',
  },
  'text-h3': {
    'font-family': 'var(--font-heading)',
    'text-transform': 'none',
    'font-size': '3rem',
    'font-weight': '400',
    'line-height': '1.05',
    'letter-spacing': 'normal',
  },
  'text-h4': {
    'font-family': 'var(--font-heading)',
    'text-transform': 'none',
    'font-size': '2.125rem',
    'font-weight': '400',
    'line-height': '1.175',
    'letter-spacing': '.0073529412em',
  },
  'text-h5': {
    'font-family': 'var(--font-heading)',
    'text-transform': 'none',
    'font-size': '1.5rem',
    'font-weight': '400',
    'line-height': '1.333',
    'letter-spacing': 'normal',
  },
  'text-h6': {
    'font-family': 'var(--font-heading)',
    'text-transform': 'none',
    'font-size': '1.25rem',
    'font-weight': '500',
    'line-height': '1.6',
    'letter-spacing': '.0125em',
  },
  'text-subtitle-1': {
    'font-family': 'var(--font-body)',
    'text-transform': 'none',
    'font-size': '1rem',
    'font-weight': '400',
    'line-height': '1.75',
    'letter-spacing': '.009375em',
  },
  'text-subtitle-2': {
    'font-family': 'var(--font-body)',
    'text-transform': 'none',
    'font-size': '.875rem',
    'font-weight': '500',
    'line-height': '1.6',
    'letter-spacing': '.0071428571em',
  },
  'text-body-1': {
    'font-family': 'var(--font-body)',
    'text-transform': 'none',
    'font-size': '1rem',
    'font-weight': '400',
    'line-height': '1.5',
    'letter-spacing': '.03125em',
  },
  'text-body-2': {
    'font-family': 'var(--font-body)',
    'text-transform': 'none',
    'font-size': '.875rem',
    'font-weight': '400',
    'line-height': '1.425',
    'letter-spacing': '.0178571429em',
  },
  'text-button': {
    'font-family': 'var(--font-body)',
    'text-transform': 'uppercase',
    'font-size': '.875rem',
    'font-weight': '500',
    'line-height': '2.6',
    'letter-spacing': '.0892857143em',
  },
  'text-caption': {
    'font-family': 'var(--font-body)',
    'text-transform': 'none',
    'font-size': '.75rem',
    'font-weight': '400',
    'line-height': '1.667',
    'letter-spacing': '.0333333333em',
  },
  'text-overline': {
    'font-family': 'var(--font-body)',
    'text-transform': 'uppercase',
    'font-size': '.75rem',
    'font-weight': '500',
    'line-height': '2.667',
    'letter-spacing': '.1666666667em',
  },
})
